// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemCategory enum for different types of rocket parts
type ItemCategory int32

const (
	ItemCategory_ITEM_CATEGORY_UNSPECIFIED  ItemCategory = 0
	ItemCategory_ITEM_CATEGORY_ENGINES      ItemCategory = 1 // Rocket engines
	ItemCategory_ITEM_CATEGORY_FUEL_TANKS   ItemCategory = 2 // Fuel storage tanks
	ItemCategory_ITEM_CATEGORY_NAVIGATION   ItemCategory = 3 // Navigation systems
	ItemCategory_ITEM_CATEGORY_STRUCTURAL   ItemCategory = 4 // Structural components
	ItemCategory_ITEM_CATEGORY_ELECTRONICS  ItemCategory = 5 // Electronic systems
	ItemCategory_ITEM_CATEGORY_LIFE_SUPPORT ItemCategory = 6 // Life support systems
	ItemCategory_ITEM_CATEGORY_PAYLOAD      ItemCategory = 7 // Payload components
	ItemCategory_ITEM_CATEGORY_LANDING_GEAR ItemCategory = 8 // Landing gear systems
)

// Enum value maps for ItemCategory.
var (
	ItemCategory_name = map[int32]string{
		0: "ITEM_CATEGORY_UNSPECIFIED",
		1: "ITEM_CATEGORY_ENGINES",
		2: "ITEM_CATEGORY_FUEL_TANKS",
		3: "ITEM_CATEGORY_NAVIGATION",
		4: "ITEM_CATEGORY_STRUCTURAL",
		5: "ITEM_CATEGORY_ELECTRONICS",
		6: "ITEM_CATEGORY_LIFE_SUPPORT",
		7: "ITEM_CATEGORY_PAYLOAD",
		8: "ITEM_CATEGORY_LANDING_GEAR",
	}
	ItemCategory_value = map[string]int32{
		"ITEM_CATEGORY_UNSPECIFIED":  0,
		"ITEM_CATEGORY_ENGINES":      1,
		"ITEM_CATEGORY_FUEL_TANKS":   2,
		"ITEM_CATEGORY_NAVIGATION":   3,
		"ITEM_CATEGORY_STRUCTURAL":   4,
		"ITEM_CATEGORY_ELECTRONICS":  5,
		"ITEM_CATEGORY_LIFE_SUPPORT": 6,
		"ITEM_CATEGORY_PAYLOAD":      7,
		"ITEM_CATEGORY_LANDING_GEAR": 8,
	}
)

func (x ItemCategory) Enum() *ItemCategory {
	p := new(ItemCategory)
	*p = x
	return p
}

func (x ItemCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inventory_inventory_proto_enumTypes[0].Descriptor()
}

func (ItemCategory) Type() protoreflect.EnumType {
	return &file_proto_inventory_inventory_proto_enumTypes[0]
}

func (x ItemCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemCategory.Descriptor instead.
func (ItemCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

// ItemStatus enum for item lifecycle states
type ItemStatus int32

const (
	ItemStatus_ITEM_STATUS_UNSPECIFIED  ItemStatus = 0
	ItemStatus_ITEM_STATUS_ACTIVE       ItemStatus = 1 // Available for orders
	ItemStatus_ITEM_STATUS_DISCONTINUED ItemStatus = 2 // No longer available
	ItemStatus_ITEM_STATUS_OUT_OF_STOCK ItemStatus = 3 // Temporarily out of stock
	ItemStatus_ITEM_STATUS_BACKORDERED  ItemStatus = 4 // On backorder
	ItemStatus_ITEM_STATUS_INCOMING     ItemStatus = 5 // New stock incoming
)

// Enum value maps for ItemStatus.
var (
	ItemStatus_name = map[int32]string{
		0: "ITEM_STATUS_UNSPECIFIED",
		1: "ITEM_STATUS_ACTIVE",
		2: "ITEM_STATUS_DISCONTINUED",
		3: "ITEM_STATUS_OUT_OF_STOCK",
		4: "ITEM_STATUS_BACKORDERED",
		5: "ITEM_STATUS_INCOMING",
	}
	ItemStatus_value = map[string]int32{
		"ITEM_STATUS_UNSPECIFIED":  0,
		"ITEM_STATUS_ACTIVE":       1,
		"ITEM_STATUS_DISCONTINUED": 2,
		"ITEM_STATUS_OUT_OF_STOCK": 3,
		"ITEM_STATUS_BACKORDERED":  4,
		"ITEM_STATUS_INCOMING":     5,
	}
)

func (x ItemStatus) Enum() *ItemStatus {
	p := new(ItemStatus)
	*p = x
	return p
}

func (x ItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inventory_inventory_proto_enumTypes[1].Descriptor()
}

func (ItemStatus) Type() protoreflect.EnumType {
	return &file_proto_inventory_inventory_proto_enumTypes[1]
}

func (x ItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemStatus.Descriptor instead.
func (ItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

// CheckAvailabilityRequest contains items to check for availability
type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*ItemAvailabilityCheck `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // Items to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAvailabilityRequest) GetItems() []*ItemAvailabilityCheck {
	if x != nil {
		return x.Items
	}
	return nil
}

// ItemAvailabilityCheck represents a single item availability check
type ItemAvailabilityCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`            // Item SKU to check
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // Quantity needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAvailabilityCheck) Reset() {
	*x = ItemAvailabilityCheck{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAvailabilityCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAvailabilityCheck) ProtoMessage() {}

func (x *ItemAvailabilityCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAvailabilityCheck.ProtoReflect.Descriptor instead.
func (*ItemAvailabilityCheck) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ItemAvailabilityCheck) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ItemAvailabilityCheck) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// CheckAvailabilityResponse contains availability results
type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	AllAvailable  bool                      `protobuf:"varint,1,opt,name=all_available,json=allAvailable,proto3" json:"all_available,omitempty"` // True if all items are available
	Results       []*ItemAvailabilityResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`                                // Per-item availability results
	Message       string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                // Summary message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAvailabilityResponse) GetAllAvailable() bool {
	if x != nil {
		return x.AllAvailable
	}
	return false
}

func (x *CheckAvailabilityResponse) GetResults() []*ItemAvailabilityResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CheckAvailabilityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ItemAvailabilityResult contains availability info for a single item
type ItemAvailabilityResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sku               string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`                                                       // Item SKU
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                     // Item name
	Available         bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`                                          // Whether requested quantity is available
	RequestedQuantity int32                  `protobuf:"varint,4,opt,name=requested_quantity,json=requestedQuantity,proto3" json:"requested_quantity,omitempty"` // Quantity requested
	AvailableQuantity int32                  `protobuf:"varint,5,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"` // Quantity available
	ReservedQuantity  int32                  `protobuf:"varint,6,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`    // Quantity currently reserved
	Reason            string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`                                                 // Reason if not available
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemAvailabilityResult) Reset() {
	*x = ItemAvailabilityResult{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAvailabilityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAvailabilityResult) ProtoMessage() {}

func (x *ItemAvailabilityResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAvailabilityResult.ProtoReflect.Descriptor instead.
func (*ItemAvailabilityResult) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ItemAvailabilityResult) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ItemAvailabilityResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemAvailabilityResult) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ItemAvailabilityResult) GetRequestedQuantity() int32 {
	if x != nil {
		return x.RequestedQuantity
	}
	return 0
}

func (x *ItemAvailabilityResult) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *ItemAvailabilityResult) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

func (x *ItemAvailabilityResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReserveItemsRequest creates reservations for order items
type ReserveItemsRequest struct {
	state                      protoimpl.MessageState    `protogen:"open.v1"`
	OrderId                    string                    `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                                                             // Order identifier
	Items                      []*ItemReservationRequest `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                                                                                // Items to reserve
	ReservationDurationMinutes int32                     `protobuf:"varint,3,opt,name=reservation_duration_minutes,json=reservationDurationMinutes,proto3" json:"reservation_duration_minutes,omitempty"` // How long to hold reservations
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ReserveItemsRequest) Reset() {
	*x = ReserveItemsRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsRequest) ProtoMessage() {}

func (x *ReserveItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveItemsRequest) GetItems() []*ItemReservationRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveItemsRequest) GetReservationDurationMinutes() int32 {
	if x != nil {
		return x.ReservationDurationMinutes
	}
	return 0
}

// ItemReservationRequest represents a single item reservation
type ItemReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`            // Item SKU
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // Quantity to reserve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReservationRequest) Reset() {
	*x = ItemReservationRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReservationRequest) ProtoMessage() {}

func (x *ItemReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReservationRequest.ProtoReflect.Descriptor instead.
func (*ItemReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ItemReservationRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ItemReservationRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// ReserveItemsResponse contains reservation results
type ReserveItemsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Success       bool                     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                 // Whether all reservations succeeded
	ReservationId string                   `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"` // Unique reservation identifier
	Results       []*ItemReservationResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`                                  // Per-item reservation results
	ExpiresAt     *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`             // When reservations expire
	Message       string                   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                  // Result message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsResponse) Reset() {
	*x = ReserveItemsResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsResponse) ProtoMessage() {}

func (x *ReserveItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsResponse.ProtoReflect.Descriptor instead.
func (*ReserveItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveItemsResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveItemsResponse) GetResults() []*ItemReservationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ReserveItemsResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ReserveItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ItemReservationResult contains reservation info for a single item
type ItemReservationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`                                          // Item SKU
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // Item name
	Reserved      bool                   `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`                               // Whether reservation succeeded
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                               // Quantity reserved
	ReservationId string                 `protobuf:"bytes,5,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"` // Individual reservation ID
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                    // Reason if reservation failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReservationResult) Reset() {
	*x = ItemReservationResult{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReservationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReservationResult) ProtoMessage() {}

func (x *ItemReservationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReservationResult.ProtoReflect.Descriptor instead.
func (*ItemReservationResult) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ItemReservationResult) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ItemReservationResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemReservationResult) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *ItemReservationResult) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemReservationResult) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ItemReservationResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ConfirmReservationRequest confirms reserved items
type ConfirmReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                   // Order identifier
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"` // Reservation to confirm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmReservationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

// ConfirmReservationResponse contains confirmation result
type ConfirmReservationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Success       bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                           // Whether confirmation succeeded
	Results       []*ItemConfirmationResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`                            // Per-item confirmation results
	ConfirmedAt   *timestamppb.Timestamp    `protobuf:"bytes,3,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"` // When confirmed
	Message       string                    `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                            // Result message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationResponse) Reset() {
	*x = ConfirmReservationResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationResponse) ProtoMessage() {}

func (x *ConfirmReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmReservationResponse) GetResults() []*ItemConfirmationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ConfirmReservationResponse) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

func (x *ConfirmReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ItemConfirmationResult contains confirmation info for a single item
type ItemConfirmationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`              // Item SKU
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`            // Item name
	Confirmed     bool                   `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"` // Whether confirmation succeeded
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`   // Quantity confirmed
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`        // Reason if confirmation failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemConfirmationResult) Reset() {
	*x = ItemConfirmationResult{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemConfirmationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemConfirmationResult) ProtoMessage() {}

func (x *ItemConfirmationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemConfirmationResult.ProtoReflect.Descriptor instead.
func (*ItemConfirmationResult) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ItemConfirmationResult) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ItemConfirmationResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemConfirmationResult) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *ItemConfirmationResult) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemConfirmationResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReleaseReservationRequest releases reserved items
type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                   // Order identifier
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"` // Reservation to release
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                    // Reason for release
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseReservationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseReservationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReleaseReservationResponse contains release result
type ReleaseReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // Whether release succeeded
	Results       []*ItemReleaseResult   `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`                         // Per-item release results
	ReleasedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"` // When released
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                         // Result message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseReservationResponse) GetResults() []*ItemReleaseResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ReleaseReservationResponse) GetReleasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleasedAt
	}
	return nil
}

func (x *ReleaseReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ItemReleaseResult contains release info for a single item
type ItemReleaseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`            // Item SKU
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`          // Item name
	Released      bool                   `protobuf:"varint,3,opt,name=released,proto3" json:"released,omitempty"` // Whether release succeeded
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"` // Quantity released back to stock
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`      // Reason if release failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReleaseResult) Reset() {
	*x = ItemReleaseResult{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReleaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReleaseResult) ProtoMessage() {}

func (x *ItemReleaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReleaseResult.ProtoReflect.Descriptor instead.
func (*ItemReleaseResult) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *ItemReleaseResult) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ItemReleaseResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemReleaseResult) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *ItemReleaseResult) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemReleaseResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GetItemRequest retrieves a specific item
type GetItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetItemRequest_ItemId
	//	*GetItemRequest_Sku
	Identifier    isGetItemRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *GetItemRequest) GetIdentifier() isGetItemRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetItemRequest) GetItemId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetItemRequest_ItemId); ok {
			return x.ItemId
		}
	}
	return ""
}

func (x *GetItemRequest) GetSku() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetItemRequest_Sku); ok {
			return x.Sku
		}
	}
	return ""
}

type isGetItemRequest_Identifier interface {
	isGetItemRequest_Identifier()
}

type GetItemRequest_ItemId struct {
	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3,oneof"` // Get by item ID
}

type GetItemRequest_Sku struct {
	Sku string `protobuf:"bytes,2,opt,name=sku,proto3,oneof"` // Get by SKU
}

func (*GetItemRequest_ItemId) isGetItemRequest_Identifier() {}

func (*GetItemRequest_Sku) isGetItemRequest_Identifier() {}

// GetItemResponse contains item details
type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`    // Whether item was found
	Item          *InventoryItem         `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`       // Item details
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Result message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *GetItemResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SearchItemsRequest searches for items
type SearchItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                       // Search query (name, description, SKU)
	Category      ItemCategory           `protobuf:"varint,2,opt,name=category,proto3,enum=inventory.v1.ItemCategory" json:"category,omitempty"` // Filter by category (optional)
	AvailableOnly bool                   `protobuf:"varint,3,opt,name=available_only,json=availableOnly,proto3" json:"available_only,omitempty"` // Only return items with stock
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                      // Maximum results to return
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`                                    // Pagination offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsRequest) Reset() {
	*x = SearchItemsRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsRequest) ProtoMessage() {}

func (x *SearchItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsRequest.ProtoReflect.Descriptor instead.
func (*SearchItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *SearchItemsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchItemsRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *SearchItemsRequest) GetAvailableOnly() bool {
	if x != nil {
		return x.AvailableOnly
	}
	return false
}

func (x *SearchItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchItemsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// SearchItemsResponse contains search results
type SearchItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                              // Found items
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total items matching criteria
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`          // Whether more results exist
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                          // Result message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsResponse) Reset() {
	*x = SearchItemsResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsResponse) ProtoMessage() {}

func (x *SearchItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsResponse.ProtoReflect.Descriptor instead.
func (*SearchItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *SearchItemsResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchItemsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchItemsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SearchItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetLowStockItemsRequest retrieves items below threshold
type GetLowStockItemsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Category          ItemCategory           `protobuf:"varint,1,opt,name=category,proto3,enum=inventory.v1.ItemCategory" json:"category,omitempty"`             // Filter by category (optional)
	ThresholdOverride int32                  `protobuf:"varint,2,opt,name=threshold_override,json=thresholdOverride,proto3" json:"threshold_override,omitempty"` // Override default threshold
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLowStockItemsRequest) Reset() {
	*x = GetLowStockItemsRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLowStockItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLowStockItemsRequest) ProtoMessage() {}

func (x *GetLowStockItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLowStockItemsRequest.ProtoReflect.Descriptor instead.
func (*GetLowStockItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{18}
}

func (x *GetLowStockItemsRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *GetLowStockItemsRequest) GetThresholdOverride() int32 {
	if x != nil {
		return x.ThresholdOverride
	}
	return 0
}

// GetLowStockItemsResponse contains low stock items
type GetLowStockItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LowStockItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                              // Items below threshold
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total low stock items
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // Result message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLowStockItemsResponse) Reset() {
	*x = GetLowStockItemsResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLowStockItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLowStockItemsResponse) ProtoMessage() {}

func (x *GetLowStockItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLowStockItemsResponse.ProtoReflect.Descriptor instead.
func (*GetLowStockItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{19}
}

func (x *GetLowStockItemsResponse) GetItems() []*LowStockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetLowStockItemsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetLowStockItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LowStockItem represents an item below stock threshold
type LowStockItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Item             *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`                                                  // Item details
	ShortageQuantity int32                  `protobuf:"varint,2,opt,name=shortage_quantity,json=shortageQuantity,proto3" json:"shortage_quantity,omitempty"` // How much below minimum
	DaysOfStock      int32                  `protobuf:"varint,3,opt,name=days_of_stock,json=daysOfStock,proto3" json:"days_of_stock,omitempty"`              // Estimated days until out of stock
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LowStockItem) Reset() {
	*x = LowStockItem{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LowStockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LowStockItem) ProtoMessage() {}

func (x *LowStockItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LowStockItem.ProtoReflect.Descriptor instead.
func (*LowStockItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{20}
}

func (x *LowStockItem) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *LowStockItem) GetShortageQuantity() int32 {
	if x != nil {
		return x.ShortageQuantity
	}
	return 0
}

func (x *LowStockItem) GetDaysOfStock() int32 {
	if x != nil {
		return x.DaysOfStock
	}
	return 0
}

// UpdateStockRequest adds or removes stock
type UpdateStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sku            string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`                                              // Item SKU
	QuantityChange int32                  `protobuf:"varint,2,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"` // Positive to add, negative to remove
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                        // Reason for stock change
	UpdatedBy      string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`                 // Who made the change
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateStockRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

func (x *UpdateStockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateStockRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

// UpdateStockResponse contains stock update result
type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                    // Whether update succeeded
	OldStockLevel int32                  `protobuf:"varint,2,opt,name=old_stock_level,json=oldStockLevel,proto3" json:"old_stock_level,omitempty"` // Stock level before update
	NewStockLevel int32                  `protobuf:"varint,3,opt,name=new_stock_level,json=newStockLevel,proto3" json:"new_stock_level,omitempty"` // Stock level after update
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                // When updated
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                     // Result message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStockResponse) GetOldStockLevel() int32 {
	if x != nil {
		return x.OldStockLevel
	}
	return 0
}

func (x *UpdateStockResponse) GetNewStockLevel() int32 {
	if x != nil {
		return x.NewStockLevel
	}
	return 0
}

func (x *UpdateStockResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpdateStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetItemsByCategoryRequest retrieves items by category
type GetItemsByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      ItemCategory           `protobuf:"varint,1,opt,name=category,proto3,enum=inventory.v1.ItemCategory" json:"category,omitempty"` // Category to retrieve
	AvailableOnly bool                   `protobuf:"varint,2,opt,name=available_only,json=availableOnly,proto3" json:"available_only,omitempty"` // Only return items with stock
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                      // Maximum results to return
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                                    // Pagination offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsByCategoryRequest) Reset() {
	*x = GetItemsByCategoryRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsByCategoryRequest) ProtoMessage() {}

func (x *GetItemsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetItemsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{23}
}

func (x *GetItemsByCategoryRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *GetItemsByCategoryRequest) GetAvailableOnly() bool {
	if x != nil {
		return x.AvailableOnly
	}
	return false
}

func (x *GetItemsByCategoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetItemsByCategoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetItemsByCategoryResponse contains category items
type GetItemsByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                              // Items in category
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total items in category
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`          // Whether more results exist
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                          // Result message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsByCategoryResponse) Reset() {
	*x = GetItemsByCategoryResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsByCategoryResponse) ProtoMessage() {}

func (x *GetItemsByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsByCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetItemsByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{24}
}

func (x *GetItemsByCategoryResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetItemsByCategoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetItemsByCategoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetItemsByCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InventoryItem represents a rocket part in inventory
type InventoryItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                                    // Unique identifier
	Sku            string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`                                                                                                  // Stock Keeping Unit
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                                                                // Human-readable name
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                                                                  // Detailed description
	Category       ItemCategory           `protobuf:"varint,5,opt,name=category,proto3,enum=inventory.v1.ItemCategory" json:"category,omitempty"`                                                        // Item category
	StockLevel     int32                  `protobuf:"varint,6,opt,name=stock_level,json=stockLevel,proto3" json:"stock_level,omitempty"`                                                                 // Available stock
	ReservedStock  int32                  `protobuf:"varint,7,opt,name=reserved_stock,json=reservedStock,proto3" json:"reserved_stock,omitempty"`                                                        // Reserved stock
	TotalStock     int32                  `protobuf:"varint,8,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"`                                                                 // Total stock
	MinStockLevel  int32                  `protobuf:"varint,9,opt,name=min_stock_level,json=minStockLevel,proto3" json:"min_stock_level,omitempty"`                                                      // Minimum threshold
	MaxStockLevel  int32                  `protobuf:"varint,10,opt,name=max_stock_level,json=maxStockLevel,proto3" json:"max_stock_level,omitempty"`                                                     // Maximum capacity
	UnitPrice      *Money                 `protobuf:"bytes,11,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`                                                                    // Price per unit
	Weight         float64                `protobuf:"fixed64,12,opt,name=weight,proto3" json:"weight,omitempty"`                                                                                         // Weight in kg
	Dimensions     *Dimensions            `protobuf:"bytes,13,opt,name=dimensions,proto3" json:"dimensions,omitempty"`                                                                                   // Physical dimensions
	Specifications map[string]string      `protobuf:"bytes,14,rep,name=specifications,proto3" json:"specifications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Technical specs
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                                    // Creation timestamp
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                                    // Last update timestamp
	Version        int32                  `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`                                                                                        // Version for optimistic locking
	Status         ItemStatus             `protobuf:"varint,18,opt,name=status,proto3,enum=inventory.v1.ItemStatus" json:"status,omitempty"`                                                             // Current status
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{25}
}

func (x *InventoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InventoryItem) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *InventoryItem) GetStockLevel() int32 {
	if x != nil {
		return x.StockLevel
	}
	return 0
}

func (x *InventoryItem) GetReservedStock() int32 {
	if x != nil {
		return x.ReservedStock
	}
	return 0
}

func (x *InventoryItem) GetTotalStock() int32 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *InventoryItem) GetMinStockLevel() int32 {
	if x != nil {
		return x.MinStockLevel
	}
	return 0
}

func (x *InventoryItem) GetMaxStockLevel() int32 {
	if x != nil {
		return x.MaxStockLevel
	}
	return 0
}

func (x *InventoryItem) GetUnitPrice() *Money {
	if x != nil {
		return x.UnitPrice
	}
	return nil
}

func (x *InventoryItem) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *InventoryItem) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *InventoryItem) GetSpecifications() map[string]string {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *InventoryItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InventoryItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *InventoryItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InventoryItem) GetStatus() ItemStatus {
	if x != nil {
		return x.Status
	}
	return ItemStatus_ITEM_STATUS_UNSPECIFIED
}

// Money represents currency amounts
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`   // Monetary amount
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // Currency code (e.g., "USD")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{26}
}

func (x *Money) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Dimensions represents physical dimensions
type Dimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        float64                `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"` // Length in meters
	Width         float64                `protobuf:"fixed64,2,opt,name=width,proto3" json:"width,omitempty"`   // Width in meters
	Height        float64                `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"` // Height in meters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{27}
}

func (x *Dimensions) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Dimensions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Dimensions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_proto_inventory_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/inventory/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\x18CheckAvailabilityRequest\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.inventory.v1.ItemAvailabilityCheckR\x05items\"E\n" +
	"\x15ItemAvailabilityCheck\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x9a\x01\n" +
	"\x19CheckAvailabilityResponse\x12#\n" +
	"\rall_available\x18\x01 \x01(\bR\fallAvailable\x12>\n" +
	"\aresults\x18\x02 \x03(\v2$.inventory.v1.ItemAvailabilityResultR\aresults\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xff\x01\n" +
	"\x16ItemAvailabilityResult\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12-\n" +
	"\x12requested_quantity\x18\x04 \x01(\x05R\x11requestedQuantity\x12-\n" +
	"\x12available_quantity\x18\x05 \x01(\x05R\x11availableQuantity\x12+\n" +
	"\x11reserved_quantity\x18\x06 \x01(\x05R\x10reservedQuantity\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"\xae\x01\n" +
	"\x13ReserveItemsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12:\n" +
	"\x05items\x18\x02 \x03(\v2$.inventory.v1.ItemReservationRequestR\x05items\x12@\n" +
	"\x1creservation_duration_minutes\x18\x03 \x01(\x05R\x1areservationDurationMinutes\"F\n" +
	"\x16ItemReservationRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xeb\x01\n" +
	"\x14ReserveItemsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12=\n" +
	"\aresults\x18\x03 \x03(\v2#.inventory.v1.ItemReservationResultR\aresults\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xb4\x01\n" +
	"\x15ItemReservationResult\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\breserved\x18\x03 \x01(\bR\breserved\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12%\n" +
	"\x0ereservation_id\x18\x05 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"]\n" +
	"\x19ConfirmReservationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\"\xcf\x01\n" +
	"\x1aConfirmReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\aresults\x18\x02 \x03(\v2$.inventory.v1.ItemConfirmationResultR\aresults\x12=\n" +
	"\fconfirmed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x90\x01\n" +
	"\x16ItemConfirmationResult\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tconfirmed\x18\x03 \x01(\bR\tconfirmed\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"u\n" +
	"\x19ReleaseReservationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xc8\x01\n" +
	"\x1aReleaseReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\aresults\x18\x02 \x03(\v2\x1f.inventory.v1.ItemReleaseResultR\aresults\x12;\n" +
	"\vreleased_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"releasedAt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x89\x01\n" +
	"\x11ItemReleaseResult\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\breleased\x18\x03 \x01(\bR\breleased\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"M\n" +
	"\x0eGetItemRequest\x12\x19\n" +
	"\aitem_id\x18\x01 \x01(\tH\x00R\x06itemId\x12\x12\n" +
	"\x03sku\x18\x02 \x01(\tH\x00R\x03skuB\f\n" +
	"\n" +
	"identifier\"r\n" +
	"\x0fGetItemResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12/\n" +
	"\x04item\x18\x02 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb7\x01\n" +
	"\x12SearchItemsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x126\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1a.inventory.v1.ItemCategoryR\bcategory\x12%\n" +
	"\x0eavailable_only\x18\x03 \x01(\bR\ravailableOnly\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"\x9e\x01\n" +
	"\x13SearchItemsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.inventory.v1.InventoryItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x80\x01\n" +
	"\x17GetLowStockItemsRequest\x126\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1a.inventory.v1.ItemCategoryR\bcategory\x12-\n" +
	"\x12threshold_override\x18\x02 \x01(\x05R\x11thresholdOverride\"\x87\x01\n" +
	"\x18GetLowStockItemsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.inventory.v1.LowStockItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x90\x01\n" +
	"\fLowStockItem\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\x12+\n" +
	"\x11shortage_quantity\x18\x02 \x01(\x05R\x10shortageQuantity\x12\"\n" +
	"\rdays_of_stock\x18\x03 \x01(\x05R\vdaysOfStock\"\x86\x01\n" +
	"\x12UpdateStockRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12'\n" +
	"\x0fquantity_change\x18\x02 \x01(\x05R\x0equantityChange\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\"\xd4\x01\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fold_stock_level\x18\x02 \x01(\x05R\roldStockLevel\x12&\n" +
	"\x0fnew_stock_level\x18\x03 \x01(\x05R\rnewStockLevel\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xa8\x01\n" +
	"\x19GetItemsByCategoryRequest\x126\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1a.inventory.v1.ItemCategoryR\bcategory\x12%\n" +
	"\x0eavailable_only\x18\x02 \x01(\bR\ravailableOnly\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xa5\x01\n" +
	"\x1aGetItemsByCategoryResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.inventory.v1.InventoryItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xbc\x06\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x126\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x1a.inventory.v1.ItemCategoryR\bcategory\x12\x1f\n" +
	"\vstock_level\x18\x06 \x01(\x05R\n" +
	"stockLevel\x12%\n" +
	"\x0ereserved_stock\x18\a \x01(\x05R\rreservedStock\x12\x1f\n" +
	"\vtotal_stock\x18\b \x01(\x05R\n" +
	"totalStock\x12&\n" +
	"\x0fmin_stock_level\x18\t \x01(\x05R\rminStockLevel\x12&\n" +
	"\x0fmax_stock_level\x18\n" +
	" \x01(\x05R\rmaxStockLevel\x122\n" +
	"\n" +
	"unit_price\x18\v \x01(\v2\x13.inventory.v1.MoneyR\tunitPrice\x12\x16\n" +
	"\x06weight\x18\f \x01(\x01R\x06weight\x128\n" +
	"\n" +
	"dimensions\x18\r \x01(\v2\x18.inventory.v1.DimensionsR\n" +
	"dimensions\x12W\n" +
	"\x0especifications\x18\x0e \x03(\v2/.inventory.v1.InventoryItem.SpecificationsEntryR\x0especifications\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x11 \x01(\x05R\aversion\x120\n" +
	"\x06status\x18\x12 \x01(\x0e2\x18.inventory.v1.ItemStatusR\x06status\x1aA\n" +
	"\x13SpecificationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"R\n" +
	"\n" +
	"Dimensions\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x01R\x06height*\x9c\x02\n" +
	"\fItemCategory\x12\x1d\n" +
	"\x19ITEM_CATEGORY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ITEM_CATEGORY_ENGINES\x10\x01\x12\x1c\n" +
	"\x18ITEM_CATEGORY_FUEL_TANKS\x10\x02\x12\x1c\n" +
	"\x18ITEM_CATEGORY_NAVIGATION\x10\x03\x12\x1c\n" +
	"\x18ITEM_CATEGORY_STRUCTURAL\x10\x04\x12\x1d\n" +
	"\x19ITEM_CATEGORY_ELECTRONICS\x10\x05\x12\x1e\n" +
	"\x1aITEM_CATEGORY_LIFE_SUPPORT\x10\x06\x12\x19\n" +
	"\x15ITEM_CATEGORY_PAYLOAD\x10\a\x12\x1e\n" +
	"\x1aITEM_CATEGORY_LANDING_GEAR\x10\b*\xb4\x01\n" +
	"\n" +
	"ItemStatus\x12\x1b\n" +
	"\x17ITEM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ITEM_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18ITEM_STATUS_DISCONTINUED\x10\x02\x12\x1c\n" +
	"\x18ITEM_STATUS_OUT_OF_STOCK\x10\x03\x12\x1b\n" +
	"\x17ITEM_STATUS_BACKORDERED\x10\x04\x12\x18\n" +
	"\x14ITEM_STATUS_INCOMING\x10\x052\xdd\x06\n" +
	"\x10InventoryService\x12d\n" +
	"\x11CheckAvailability\x12&.inventory.v1.CheckAvailabilityRequest\x1a'.inventory.v1.CheckAvailabilityResponse\x12U\n" +
	"\fReserveItems\x12!.inventory.v1.ReserveItemsRequest\x1a\".inventory.v1.ReserveItemsResponse\x12g\n" +
	"\x12ConfirmReservation\x12'.inventory.v1.ConfirmReservationRequest\x1a(.inventory.v1.ConfirmReservationResponse\x12g\n" +
	"\x12ReleaseReservation\x12'.inventory.v1.ReleaseReservationRequest\x1a(.inventory.v1.ReleaseReservationResponse\x12F\n" +
	"\aGetItem\x12\x1c.inventory.v1.GetItemRequest\x1a\x1d.inventory.v1.GetItemResponse\x12R\n" +
	"\vSearchItems\x12 .inventory.v1.SearchItemsRequest\x1a!.inventory.v1.SearchItemsResponse\x12a\n" +
	"\x10GetLowStockItems\x12%.inventory.v1.GetLowStockItemsRequest\x1a&.inventory.v1.GetLowStockItemsResponse\x12R\n" +
	"\vUpdateStock\x12 .inventory.v1.UpdateStockRequest\x1a!.inventory.v1.UpdateStockResponse\x12g\n" +
	"\x12GetItemsByCategory\x12'.inventory.v1.GetItemsByCategoryRequest\x1a(.inventory.v1.GetItemsByCategoryResponseBOZMgithub.com/amiosamu/rocket-science/services/inventory-service/proto/inventoryb\x06proto3"

var (
	file_proto_inventory_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_inventory_proto_rawDescData []byte
)

func file_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_inventory_proto_rawDesc), len(file_proto_inventory_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_inventory_proto_rawDescData
}

var file_proto_inventory_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_inventory_inventory_proto_goTypes = []any{
	(ItemCategory)(0),                  // 0: inventory.v1.ItemCategory
	(ItemStatus)(0),                    // 1: inventory.v1.ItemStatus
	(*CheckAvailabilityRequest)(nil),   // 2: inventory.v1.CheckAvailabilityRequest
	(*ItemAvailabilityCheck)(nil),      // 3: inventory.v1.ItemAvailabilityCheck
	(*CheckAvailabilityResponse)(nil),  // 4: inventory.v1.CheckAvailabilityResponse
	(*ItemAvailabilityResult)(nil),     // 5: inventory.v1.ItemAvailabilityResult
	(*ReserveItemsRequest)(nil),        // 6: inventory.v1.ReserveItemsRequest
	(*ItemReservationRequest)(nil),     // 7: inventory.v1.ItemReservationRequest
	(*ReserveItemsResponse)(nil),       // 8: inventory.v1.ReserveItemsResponse
	(*ItemReservationResult)(nil),      // 9: inventory.v1.ItemReservationResult
	(*ConfirmReservationRequest)(nil),  // 10: inventory.v1.ConfirmReservationRequest
	(*ConfirmReservationResponse)(nil), // 11: inventory.v1.ConfirmReservationResponse
	(*ItemConfirmationResult)(nil),     // 12: inventory.v1.ItemConfirmationResult
	(*ReleaseReservationRequest)(nil),  // 13: inventory.v1.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil), // 14: inventory.v1.ReleaseReservationResponse
	(*ItemReleaseResult)(nil),          // 15: inventory.v1.ItemReleaseResult
	(*GetItemRequest)(nil),             // 16: inventory.v1.GetItemRequest
	(*GetItemResponse)(nil),            // 17: inventory.v1.GetItemResponse
	(*SearchItemsRequest)(nil),         // 18: inventory.v1.SearchItemsRequest
	(*SearchItemsResponse)(nil),        // 19: inventory.v1.SearchItemsResponse
	(*GetLowStockItemsRequest)(nil),    // 20: inventory.v1.GetLowStockItemsRequest
	(*GetLowStockItemsResponse)(nil),   // 21: inventory.v1.GetLowStockItemsResponse
	(*LowStockItem)(nil),               // 22: inventory.v1.LowStockItem
	(*UpdateStockRequest)(nil),         // 23: inventory.v1.UpdateStockRequest
	(*UpdateStockResponse)(nil),        // 24: inventory.v1.UpdateStockResponse
	(*GetItemsByCategoryRequest)(nil),  // 25: inventory.v1.GetItemsByCategoryRequest
	(*GetItemsByCategoryResponse)(nil), // 26: inventory.v1.GetItemsByCategoryResponse
	(*InventoryItem)(nil),              // 27: inventory.v1.InventoryItem
	(*Money)(nil),                      // 28: inventory.v1.Money
	(*Dimensions)(nil),                 // 29: inventory.v1.Dimensions
	nil,                                // 30: inventory.v1.InventoryItem.SpecificationsEntry
	(*timestamppb.Timestamp)(nil),      // 31: google.protobuf.Timestamp
}
var file_proto_inventory_inventory_proto_depIdxs = []int32{
	3,  // 0: inventory.v1.CheckAvailabilityRequest.items:type_name -> inventory.v1.ItemAvailabilityCheck
	5,  // 1: inventory.v1.CheckAvailabilityResponse.results:type_name -> inventory.v1.ItemAvailabilityResult
	7,  // 2: inventory.v1.ReserveItemsRequest.items:type_name -> inventory.v1.ItemReservationRequest
	9,  // 3: inventory.v1.ReserveItemsResponse.results:type_name -> inventory.v1.ItemReservationResult
	31, // 4: inventory.v1.ReserveItemsResponse.expires_at:type_name -> google.protobuf.Timestamp
	12, // 5: inventory.v1.ConfirmReservationResponse.results:type_name -> inventory.v1.ItemConfirmationResult
	31, // 6: inventory.v1.ConfirmReservationResponse.confirmed_at:type_name -> google.protobuf.Timestamp
	15, // 7: inventory.v1.ReleaseReservationResponse.results:type_name -> inventory.v1.ItemReleaseResult
	31, // 8: inventory.v1.ReleaseReservationResponse.released_at:type_name -> google.protobuf.Timestamp
	27, // 9: inventory.v1.GetItemResponse.item:type_name -> inventory.v1.InventoryItem
	0,  // 10: inventory.v1.SearchItemsRequest.category:type_name -> inventory.v1.ItemCategory
	27, // 11: inventory.v1.SearchItemsResponse.items:type_name -> inventory.v1.InventoryItem
	0,  // 12: inventory.v1.GetLowStockItemsRequest.category:type_name -> inventory.v1.ItemCategory
	22, // 13: inventory.v1.GetLowStockItemsResponse.items:type_name -> inventory.v1.LowStockItem
	27, // 14: inventory.v1.LowStockItem.item:type_name -> inventory.v1.InventoryItem
	31, // 15: inventory.v1.UpdateStockResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 16: inventory.v1.GetItemsByCategoryRequest.category:type_name -> inventory.v1.ItemCategory
	27, // 17: inventory.v1.GetItemsByCategoryResponse.items:type_name -> inventory.v1.InventoryItem
	0,  // 18: inventory.v1.InventoryItem.category:type_name -> inventory.v1.ItemCategory
	28, // 19: inventory.v1.InventoryItem.unit_price:type_name -> inventory.v1.Money
	29, // 20: inventory.v1.InventoryItem.dimensions:type_name -> inventory.v1.Dimensions
	30, // 21: inventory.v1.InventoryItem.specifications:type_name -> inventory.v1.InventoryItem.SpecificationsEntry
	31, // 22: inventory.v1.InventoryItem.created_at:type_name -> google.protobuf.Timestamp
	31, // 23: inventory.v1.InventoryItem.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 24: inventory.v1.InventoryItem.status:type_name -> inventory.v1.ItemStatus
	2,  // 25: inventory.v1.InventoryService.CheckAvailability:input_type -> inventory.v1.CheckAvailabilityRequest
	6,  // 26: inventory.v1.InventoryService.ReserveItems:input_type -> inventory.v1.ReserveItemsRequest
	10, // 27: inventory.v1.InventoryService.ConfirmReservation:input_type -> inventory.v1.ConfirmReservationRequest
	13, // 28: inventory.v1.InventoryService.ReleaseReservation:input_type -> inventory.v1.ReleaseReservationRequest
	16, // 29: inventory.v1.InventoryService.GetItem:input_type -> inventory.v1.GetItemRequest
	18, // 30: inventory.v1.InventoryService.SearchItems:input_type -> inventory.v1.SearchItemsRequest
	20, // 31: inventory.v1.InventoryService.GetLowStockItems:input_type -> inventory.v1.GetLowStockItemsRequest
	23, // 32: inventory.v1.InventoryService.UpdateStock:input_type -> inventory.v1.UpdateStockRequest
	25, // 33: inventory.v1.InventoryService.GetItemsByCategory:input_type -> inventory.v1.GetItemsByCategoryRequest
	4,  // 34: inventory.v1.InventoryService.CheckAvailability:output_type -> inventory.v1.CheckAvailabilityResponse
	8,  // 35: inventory.v1.InventoryService.ReserveItems:output_type -> inventory.v1.ReserveItemsResponse
	11, // 36: inventory.v1.InventoryService.ConfirmReservation:output_type -> inventory.v1.ConfirmReservationResponse
	14, // 37: inventory.v1.InventoryService.ReleaseReservation:output_type -> inventory.v1.ReleaseReservationResponse
	17, // 38: inventory.v1.InventoryService.GetItem:output_type -> inventory.v1.GetItemResponse
	19, // 39: inventory.v1.InventoryService.SearchItems:output_type -> inventory.v1.SearchItemsResponse
	21, // 40: inventory.v1.InventoryService.GetLowStockItems:output_type -> inventory.v1.GetLowStockItemsResponse
	24, // 41: inventory.v1.InventoryService.UpdateStock:output_type -> inventory.v1.UpdateStockResponse
	26, // 42: inventory.v1.InventoryService.GetItemsByCategory:output_type -> inventory.v1.GetItemsByCategoryResponse
	34, // [34:43] is the sub-list for method output_type
	25, // [25:34] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_inventory_inventory_proto_init() }
func file_proto_inventory_inventory_proto_init() {
	if File_proto_inventory_inventory_proto != nil {
		return
	}
	file_proto_inventory_inventory_proto_msgTypes[14].OneofWrappers = []any{
		(*GetItemRequest_ItemId)(nil),
		(*GetItemRequest_Sku)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_inventory_proto_rawDesc), len(file_proto_inventory_inventory_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_inventory_proto_depIdxs,
		EnumInfos:         file_proto_inventory_inventory_proto_enumTypes,
		MessageInfos:      file_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_inventory_proto = out.File
	file_proto_inventory_inventory_proto_goTypes = nil
	file_proto_inventory_inventory_proto_depIdxs = nil
}
