apiVersion: 1

datasources:
  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus-uid
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      timeInterval: "15s"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger-uid
    editable: true

  # Jaeger datasource for distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger-uid
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki-uid'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          { key: 'service.name', value: 'service' }
        ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'prometheus-uid'
        tags: [
          { key: 'service.name', value: 'service' },
          { key: 'job', value: 'job' }
        ]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      nodeGraph:
        enabled: true
    editable: true

  # Loki datasource for logs (if you add Loki in the future)
  # - name: Loki
  #   type: loki
  #   access: proxy
  #   url: http://loki:3100
  #   uid: loki-uid
  #   jsonData:
  #     maxLines: 1000
  #     derivedFields:
  #       - datasourceUid: jaeger-uid
  #         matcherRegex: "trace_id=(\\w+)"
  #         name: TraceID
  #         url: '$${__value.raw}'
  #   editable: true

  # Elasticsearch datasource for logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    uid: elasticsearch-uid
    database: rocket-science-logs-*
    jsonData:
      index: rocket-science-logs
      timeField: "@timestamp"
      esVersion: "8.11.0"
      includeFrozen: false
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
      interval: Daily
    editable: true

  # TestData datasource for development and testing
  - name: TestData DB
    type: testdata
    uid: testdata-uid
    editable: true 