// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: events/events.proto

package events

import (
	common "github.com/amiosamu/rocket-science/shared/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNKNOWN    OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING    OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID       OrderStatus = 2
	OrderStatus_ORDER_STATUS_ASSEMBLING OrderStatus = 3
	OrderStatus_ORDER_STATUS_ASSEMBLED  OrderStatus = 4
	OrderStatus_ORDER_STATUS_COMPLETED  OrderStatus = 5
	OrderStatus_ORDER_STATUS_CANCELLED  OrderStatus = 6
	OrderStatus_ORDER_STATUS_FAILED     OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNKNOWN",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_ASSEMBLING",
		4: "ORDER_STATUS_ASSEMBLED",
		5: "ORDER_STATUS_COMPLETED",
		6: "ORDER_STATUS_CANCELLED",
		7: "ORDER_STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNKNOWN":    0,
		"ORDER_STATUS_PENDING":    1,
		"ORDER_STATUS_PAID":       2,
		"ORDER_STATUS_ASSEMBLING": 3,
		"ORDER_STATUS_ASSEMBLED":  4,
		"ORDER_STATUS_COMPLETED":  5,
		"ORDER_STATUS_CANCELLED":  6,
		"ORDER_STATUS_FAILED":     7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_events_events_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_events_events_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{0}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNKNOWN    PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING    PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_COMPLETED  PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_FAILED     PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELLED  PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_REFUNDED   PaymentStatus = 6
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNKNOWN",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_COMPLETED",
		4: "PAYMENT_STATUS_FAILED",
		5: "PAYMENT_STATUS_CANCELLED",
		6: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNKNOWN":    0,
		"PAYMENT_STATUS_PENDING":    1,
		"PAYMENT_STATUS_PROCESSING": 2,
		"PAYMENT_STATUS_COMPLETED":  3,
		"PAYMENT_STATUS_FAILED":     4,
		"PAYMENT_STATUS_CANCELLED":  5,
		"PAYMENT_STATUS_REFUNDED":   6,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_events_events_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_events_events_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{1}
}

type AssemblyQuality int32

const (
	AssemblyQuality_ASSEMBLY_QUALITY_UNKNOWN   AssemblyQuality = 0
	AssemblyQuality_ASSEMBLY_QUALITY_EXCELLENT AssemblyQuality = 1
	AssemblyQuality_ASSEMBLY_QUALITY_GOOD      AssemblyQuality = 2
	AssemblyQuality_ASSEMBLY_QUALITY_FAIR      AssemblyQuality = 3
	AssemblyQuality_ASSEMBLY_QUALITY_POOR      AssemblyQuality = 4
)

// Enum value maps for AssemblyQuality.
var (
	AssemblyQuality_name = map[int32]string{
		0: "ASSEMBLY_QUALITY_UNKNOWN",
		1: "ASSEMBLY_QUALITY_EXCELLENT",
		2: "ASSEMBLY_QUALITY_GOOD",
		3: "ASSEMBLY_QUALITY_FAIR",
		4: "ASSEMBLY_QUALITY_POOR",
	}
	AssemblyQuality_value = map[string]int32{
		"ASSEMBLY_QUALITY_UNKNOWN":   0,
		"ASSEMBLY_QUALITY_EXCELLENT": 1,
		"ASSEMBLY_QUALITY_GOOD":      2,
		"ASSEMBLY_QUALITY_FAIR":      3,
		"ASSEMBLY_QUALITY_POOR":      4,
	}
)

func (x AssemblyQuality) Enum() *AssemblyQuality {
	p := new(AssemblyQuality)
	*p = x
	return p
}

func (x AssemblyQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssemblyQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_events_events_proto_enumTypes[2].Descriptor()
}

func (AssemblyQuality) Type() protoreflect.EnumType {
	return &file_events_events_proto_enumTypes[2]
}

func (x AssemblyQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssemblyQuality.Descriptor instead.
func (AssemblyQuality) EnumDescriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{2}
}

type ComponentType int32

const (
	ComponentType_COMPONENT_TYPE_UNKNOWN         ComponentType = 0
	ComponentType_COMPONENT_TYPE_ENGINE          ComponentType = 1
	ComponentType_COMPONENT_TYPE_FUEL_TANK       ComponentType = 2
	ComponentType_COMPONENT_TYPE_GUIDANCE_SYSTEM ComponentType = 3
	ComponentType_COMPONENT_TYPE_PAYLOAD_BAY     ComponentType = 4
	ComponentType_COMPONENT_TYPE_HEAT_SHIELD     ComponentType = 5
	ComponentType_COMPONENT_TYPE_LANDING_GEAR    ComponentType = 6
	ComponentType_COMPONENT_TYPE_COMMUNICATION   ComponentType = 7
	ComponentType_COMPONENT_TYPE_STRUCTURAL      ComponentType = 8
)

// Enum value maps for ComponentType.
var (
	ComponentType_name = map[int32]string{
		0: "COMPONENT_TYPE_UNKNOWN",
		1: "COMPONENT_TYPE_ENGINE",
		2: "COMPONENT_TYPE_FUEL_TANK",
		3: "COMPONENT_TYPE_GUIDANCE_SYSTEM",
		4: "COMPONENT_TYPE_PAYLOAD_BAY",
		5: "COMPONENT_TYPE_HEAT_SHIELD",
		6: "COMPONENT_TYPE_LANDING_GEAR",
		7: "COMPONENT_TYPE_COMMUNICATION",
		8: "COMPONENT_TYPE_STRUCTURAL",
	}
	ComponentType_value = map[string]int32{
		"COMPONENT_TYPE_UNKNOWN":         0,
		"COMPONENT_TYPE_ENGINE":          1,
		"COMPONENT_TYPE_FUEL_TANK":       2,
		"COMPONENT_TYPE_GUIDANCE_SYSTEM": 3,
		"COMPONENT_TYPE_PAYLOAD_BAY":     4,
		"COMPONENT_TYPE_HEAT_SHIELD":     5,
		"COMPONENT_TYPE_LANDING_GEAR":    6,
		"COMPONENT_TYPE_COMMUNICATION":   7,
		"COMPONENT_TYPE_STRUCTURAL":      8,
	}
)

func (x ComponentType) Enum() *ComponentType {
	p := new(ComponentType)
	*p = x
	return p
}

func (x ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_events_proto_enumTypes[3].Descriptor()
}

func (ComponentType) Type() protoreflect.EnumType {
	return &file_events_events_proto_enumTypes[3]
}

func (x ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentType.Descriptor instead.
func (ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{3}
}

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNKNOWN              NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_ORDER_CONFIRMATION   NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_PAYMENT_CONFIRMATION NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_ASSEMBLY_STARTED     NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_ASSEMBLY_COMPLETED   NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_ORDER_READY          NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_ORDER_CANCELLED      NotificationType = 6
	NotificationType_NOTIFICATION_TYPE_PAYMENT_FAILED       NotificationType = 7
	NotificationType_NOTIFICATION_TYPE_SYSTEM_ALERT         NotificationType = 8
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNKNOWN",
		1: "NOTIFICATION_TYPE_ORDER_CONFIRMATION",
		2: "NOTIFICATION_TYPE_PAYMENT_CONFIRMATION",
		3: "NOTIFICATION_TYPE_ASSEMBLY_STARTED",
		4: "NOTIFICATION_TYPE_ASSEMBLY_COMPLETED",
		5: "NOTIFICATION_TYPE_ORDER_READY",
		6: "NOTIFICATION_TYPE_ORDER_CANCELLED",
		7: "NOTIFICATION_TYPE_PAYMENT_FAILED",
		8: "NOTIFICATION_TYPE_SYSTEM_ALERT",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNKNOWN":              0,
		"NOTIFICATION_TYPE_ORDER_CONFIRMATION":   1,
		"NOTIFICATION_TYPE_PAYMENT_CONFIRMATION": 2,
		"NOTIFICATION_TYPE_ASSEMBLY_STARTED":     3,
		"NOTIFICATION_TYPE_ASSEMBLY_COMPLETED":   4,
		"NOTIFICATION_TYPE_ORDER_READY":          5,
		"NOTIFICATION_TYPE_ORDER_CANCELLED":      6,
		"NOTIFICATION_TYPE_PAYMENT_FAILED":       7,
		"NOTIFICATION_TYPE_SYSTEM_ALERT":         8,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_events_proto_enumTypes[4].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_events_events_proto_enumTypes[4]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{4}
}

type NotificationStatus int32

const (
	NotificationStatus_NOTIFICATION_STATUS_UNKNOWN   NotificationStatus = 0
	NotificationStatus_NOTIFICATION_STATUS_PENDING   NotificationStatus = 1
	NotificationStatus_NOTIFICATION_STATUS_SENT      NotificationStatus = 2
	NotificationStatus_NOTIFICATION_STATUS_DELIVERED NotificationStatus = 3
	NotificationStatus_NOTIFICATION_STATUS_FAILED    NotificationStatus = 4
	NotificationStatus_NOTIFICATION_STATUS_BOUNCED   NotificationStatus = 5
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNKNOWN",
		1: "NOTIFICATION_STATUS_PENDING",
		2: "NOTIFICATION_STATUS_SENT",
		3: "NOTIFICATION_STATUS_DELIVERED",
		4: "NOTIFICATION_STATUS_FAILED",
		5: "NOTIFICATION_STATUS_BOUNCED",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNKNOWN":   0,
		"NOTIFICATION_STATUS_PENDING":   1,
		"NOTIFICATION_STATUS_SENT":      2,
		"NOTIFICATION_STATUS_DELIVERED": 3,
		"NOTIFICATION_STATUS_FAILED":    4,
		"NOTIFICATION_STATUS_BOUNCED":   5,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_events_events_proto_enumTypes[5].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_events_events_proto_enumTypes[5]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{5}
}

// Base event structure following CloudEvents specification
type BaseEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source          string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Subject         string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	DataContentType string                 `protobuf:"bytes,6,opt,name=data_content_type,json=dataContentType,proto3" json:"data_content_type,omitempty"`
	Data            *anypb.Any             `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Extensions      map[string]string      `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SpecVersion     string                 `protobuf:"bytes,9,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"` // CloudEvents spec version
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEvent.ProtoReflect.Descriptor instead.
func (*BaseEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *BaseEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BaseEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BaseEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *BaseEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *BaseEvent) GetDataContentType() string {
	if x != nil {
		return x.DataContentType
	}
	return ""
}

func (x *BaseEvent) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BaseEvent) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *BaseEvent) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

// Event envelope for Kafka messages
type EventEnvelope struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Event             *BaseEvent              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Metadata          *common.RequestMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RetryCount        int32                   `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	OriginalTimestamp *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=original_timestamp,json=originalTimestamp,proto3" json:"original_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_events_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventEnvelope) GetEvent() *BaseEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventEnvelope) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EventEnvelope) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *EventEnvelope) GetOriginalTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.OriginalTimestamp
	}
	return nil
}

// Order-related events
type OrderCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   *common.Money          `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedEvent) Reset() {
	*x = OrderCreatedEvent{}
	mi := &file_events_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedEvent) ProtoMessage() {}

func (x *OrderCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedEvent.ProtoReflect.Descriptor instead.
func (*OrderCreatedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCreatedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCreatedEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderCreatedEvent) GetTotalAmount() *common.Money {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *OrderCreatedEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OrderPaidEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPaidEvent) Reset() {
	*x = OrderPaidEvent{}
	mi := &file_events_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaidEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaidEvent) ProtoMessage() {}

func (x *OrderPaidEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaidEvent.ProtoReflect.Descriptor instead.
func (*OrderPaidEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderPaidEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPaidEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderPaidEvent) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *OrderPaidEvent) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *OrderPaidEvent) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderPaidEvent) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

type OrderStatusChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldStatus     OrderStatus            `protobuf:"varint,3,opt,name=old_status,json=oldStatus,proto3,enum=events.OrderStatus" json:"old_status,omitempty"`
	NewStatus     OrderStatus            `protobuf:"varint,4,opt,name=new_status,json=newStatus,proto3,enum=events.OrderStatus" json:"new_status,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusChangedEvent) Reset() {
	*x = OrderStatusChangedEvent{}
	mi := &file_events_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusChangedEvent) ProtoMessage() {}

func (x *OrderStatusChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusChangedEvent.ProtoReflect.Descriptor instead.
func (*OrderStatusChangedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{4}
}

func (x *OrderStatusChangedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatusChangedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderStatusChangedEvent) GetOldStatus() OrderStatus {
	if x != nil {
		return x.OldStatus
	}
	return OrderStatus_ORDER_STATUS_UNKNOWN
}

func (x *OrderStatusChangedEvent) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_STATUS_UNKNOWN
}

func (x *OrderStatusChangedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderStatusChangedEvent) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

type OrderCancelledEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CancelledAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	RefundRequired bool                   `protobuf:"varint,5,opt,name=refund_required,json=refundRequired,proto3" json:"refund_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderCancelledEvent) Reset() {
	*x = OrderCancelledEvent{}
	mi := &file_events_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledEvent) ProtoMessage() {}

func (x *OrderCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledEvent.ProtoReflect.Descriptor instead.
func (*OrderCancelledEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{5}
}

func (x *OrderCancelledEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelledEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCancelledEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderCancelledEvent) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *OrderCancelledEvent) GetRefundRequired() bool {
	if x != nil {
		return x.RefundRequired
	}
	return false
}

// Payment-related events
type PaymentProcessedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=events.PaymentStatus" json:"status,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentProcessedEvent) Reset() {
	*x = PaymentProcessedEvent{}
	mi := &file_events_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentProcessedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentProcessedEvent) ProtoMessage() {}

func (x *PaymentProcessedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentProcessedEvent.ProtoReflect.Descriptor instead.
func (*PaymentProcessedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentProcessedEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentProcessedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentProcessedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentProcessedEvent) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentProcessedEvent) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentProcessedEvent) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentProcessedEvent) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNKNOWN
}

func (x *PaymentProcessedEvent) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

type PaymentFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	FailedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailedEvent) Reset() {
	*x = PaymentFailedEvent{}
	mi := &file_events_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailedEvent) ProtoMessage() {}

func (x *PaymentFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailedEvent.ProtoReflect.Descriptor instead.
func (*PaymentFailedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentFailedEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentFailedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentFailedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentFailedEvent) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentFailedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PaymentFailedEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PaymentFailedEvent) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

// Assembly-related events
type AssemblyStartedEvent struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AssemblyId               string                 `protobuf:"bytes,1,opt,name=assembly_id,json=assemblyId,proto3" json:"assembly_id,omitempty"`
	OrderId                  string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId                   string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Components               []*RocketComponent     `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	StartedAt                *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EstimatedDurationSeconds int32                  `protobuf:"varint,6,opt,name=estimated_duration_seconds,json=estimatedDurationSeconds,proto3" json:"estimated_duration_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AssemblyStartedEvent) Reset() {
	*x = AssemblyStartedEvent{}
	mi := &file_events_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyStartedEvent) ProtoMessage() {}

func (x *AssemblyStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyStartedEvent.ProtoReflect.Descriptor instead.
func (*AssemblyStartedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{8}
}

func (x *AssemblyStartedEvent) GetAssemblyId() string {
	if x != nil {
		return x.AssemblyId
	}
	return ""
}

func (x *AssemblyStartedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AssemblyStartedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssemblyStartedEvent) GetComponents() []*RocketComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *AssemblyStartedEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AssemblyStartedEvent) GetEstimatedDurationSeconds() int32 {
	if x != nil {
		return x.EstimatedDurationSeconds
	}
	return 0
}

type AssemblyCompletedEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AssemblyId            string                 `protobuf:"bytes,1,opt,name=assembly_id,json=assemblyId,proto3" json:"assembly_id,omitempty"`
	OrderId               string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId                string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActualDurationSeconds int32                  `protobuf:"varint,4,opt,name=actual_duration_seconds,json=actualDurationSeconds,proto3" json:"actual_duration_seconds,omitempty"`
	Quality               AssemblyQuality        `protobuf:"varint,5,opt,name=quality,proto3,enum=events.AssemblyQuality" json:"quality,omitempty"`
	CompletedAt           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AssemblyCompletedEvent) Reset() {
	*x = AssemblyCompletedEvent{}
	mi := &file_events_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyCompletedEvent) ProtoMessage() {}

func (x *AssemblyCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyCompletedEvent.ProtoReflect.Descriptor instead.
func (*AssemblyCompletedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{9}
}

func (x *AssemblyCompletedEvent) GetAssemblyId() string {
	if x != nil {
		return x.AssemblyId
	}
	return ""
}

func (x *AssemblyCompletedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AssemblyCompletedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssemblyCompletedEvent) GetActualDurationSeconds() int32 {
	if x != nil {
		return x.ActualDurationSeconds
	}
	return 0
}

func (x *AssemblyCompletedEvent) GetQuality() AssemblyQuality {
	if x != nil {
		return x.Quality
	}
	return AssemblyQuality_ASSEMBLY_QUALITY_UNKNOWN
}

func (x *AssemblyCompletedEvent) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type AssemblyFailedEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AssemblyId       string                 `protobuf:"bytes,1,opt,name=assembly_id,json=assemblyId,proto3" json:"assembly_id,omitempty"`
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason           string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	FailedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	FailedComponents []string               `protobuf:"bytes,7,rep,name=failed_components,json=failedComponents,proto3" json:"failed_components,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssemblyFailedEvent) Reset() {
	*x = AssemblyFailedEvent{}
	mi := &file_events_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyFailedEvent) ProtoMessage() {}

func (x *AssemblyFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyFailedEvent.ProtoReflect.Descriptor instead.
func (*AssemblyFailedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{10}
}

func (x *AssemblyFailedEvent) GetAssemblyId() string {
	if x != nil {
		return x.AssemblyId
	}
	return ""
}

func (x *AssemblyFailedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AssemblyFailedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssemblyFailedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AssemblyFailedEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AssemblyFailedEvent) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *AssemblyFailedEvent) GetFailedComponents() []string {
	if x != nil {
		return x.FailedComponents
	}
	return nil
}

// Inventory-related events
type InventoryReservedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*InventoryItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	ReservedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=reserved_at,json=reservedAt,proto3" json:"reserved_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReservedEvent) Reset() {
	*x = InventoryReservedEvent{}
	mi := &file_events_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReservedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReservedEvent) ProtoMessage() {}

func (x *InventoryReservedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReservedEvent.ProtoReflect.Descriptor instead.
func (*InventoryReservedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{11}
}

func (x *InventoryReservedEvent) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *InventoryReservedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryReservedEvent) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InventoryReservedEvent) GetReservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservedAt
	}
	return nil
}

func (x *InventoryReservedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type InventoryReleasedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*InventoryItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ReleasedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReleasedEvent) Reset() {
	*x = InventoryReleasedEvent{}
	mi := &file_events_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReleasedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReleasedEvent) ProtoMessage() {}

func (x *InventoryReleasedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReleasedEvent.ProtoReflect.Descriptor instead.
func (*InventoryReleasedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{12}
}

func (x *InventoryReleasedEvent) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *InventoryReleasedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryReleasedEvent) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InventoryReleasedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InventoryReleasedEvent) GetReleasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleasedAt
	}
	return nil
}

type InventoryUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	OldQuantity   int32                  `protobuf:"varint,3,opt,name=old_quantity,json=oldQuantity,proto3" json:"old_quantity,omitempty"`
	NewQuantity   int32                  `protobuf:"varint,4,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryUpdatedEvent) Reset() {
	*x = InventoryUpdatedEvent{}
	mi := &file_events_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUpdatedEvent) ProtoMessage() {}

func (x *InventoryUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUpdatedEvent.ProtoReflect.Descriptor instead.
func (*InventoryUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{13}
}

func (x *InventoryUpdatedEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryUpdatedEvent) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *InventoryUpdatedEvent) GetOldQuantity() int32 {
	if x != nil {
		return x.OldQuantity
	}
	return 0
}

func (x *InventoryUpdatedEvent) GetNewQuantity() int32 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

func (x *InventoryUpdatedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InventoryUpdatedEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Notification-related events
type NotificationSentEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=events.NotificationType" json:"type,omitempty"`
	Channel        string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"` // email, sms, telegram, push
	Subject        string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status         NotificationStatus     `protobuf:"varint,7,opt,name=status,proto3,enum=events.NotificationStatus" json:"status,omitempty"`
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationSentEvent) Reset() {
	*x = NotificationSentEvent{}
	mi := &file_events_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSentEvent) ProtoMessage() {}

func (x *NotificationSentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSentEvent.ProtoReflect.Descriptor instead.
func (*NotificationSentEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{14}
}

func (x *NotificationSentEvent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationSentEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationSentEvent) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNKNOWN
}

func (x *NotificationSentEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotificationSentEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationSentEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationSentEvent) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNKNOWN
}

func (x *NotificationSentEvent) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type NotificationFailedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=events.NotificationType" json:"type,omitempty"`
	Channel        string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	FailedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	RetryCount     int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationFailedEvent) Reset() {
	*x = NotificationFailedEvent{}
	mi := &file_events_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationFailedEvent) ProtoMessage() {}

func (x *NotificationFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationFailedEvent.ProtoReflect.Descriptor instead.
func (*NotificationFailedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{15}
}

func (x *NotificationFailedEvent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationFailedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationFailedEvent) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNKNOWN
}

func (x *NotificationFailedEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotificationFailedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NotificationFailedEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *NotificationFailedEvent) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *NotificationFailedEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// User-related events
type UserCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedEvent) Reset() {
	*x = UserCreatedEvent{}
	mi := &file_events_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedEvent) ProtoMessage() {}

func (x *UserCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedEvent.ProtoReflect.Descriptor instead.
func (*UserCreatedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{16}
}

func (x *UserCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreatedEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreatedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreatedEvent) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserCreatedEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserSessionStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionStartedEvent) Reset() {
	*x = UserSessionStartedEvent{}
	mi := &file_events_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionStartedEvent) ProtoMessage() {}

func (x *UserSessionStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionStartedEvent.ProtoReflect.Descriptor instead.
func (*UserSessionStartedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{17}
}

func (x *UserSessionStartedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserSessionStartedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSessionStartedEvent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UserSessionStartedEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *UserSessionStartedEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *UserSessionStartedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type UserSessionEndedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // logout, timeout, forced
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionEndedEvent) Reset() {
	*x = UserSessionEndedEvent{}
	mi := &file_events_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionEndedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionEndedEvent) ProtoMessage() {}

func (x *UserSessionEndedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionEndedEvent.ProtoReflect.Descriptor instead.
func (*UserSessionEndedEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{18}
}

func (x *UserSessionEndedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserSessionEndedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSessionEndedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UserSessionEndedEvent) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

// Supporting data structures
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     *common.Money          `protobuf:"bytes,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    *common.Money          `protobuf:"bytes,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_events_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{19}
}

func (x *OrderItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() *common.Money {
	if x != nil {
		return x.UnitPrice
	}
	return nil
}

func (x *OrderItem) GetTotalPrice() *common.Money {
	if x != nil {
		return x.TotalPrice
	}
	return nil
}

type RocketComponent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComponentId    string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	ComponentName  string                 `protobuf:"bytes,2,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Type           ComponentType          `protobuf:"varint,3,opt,name=type,proto3,enum=events.ComponentType" json:"type,omitempty"`
	Specifications map[string]string      `protobuf:"bytes,4,rep,name=specifications,proto3" json:"specifications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Quantity       int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RocketComponent) Reset() {
	*x = RocketComponent{}
	mi := &file_events_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RocketComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RocketComponent) ProtoMessage() {}

func (x *RocketComponent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RocketComponent.ProtoReflect.Descriptor instead.
func (*RocketComponent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{20}
}

func (x *RocketComponent) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *RocketComponent) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *RocketComponent) GetType() ComponentType {
	if x != nil {
		return x.Type
	}
	return ComponentType_COMPONENT_TYPE_UNKNOWN
}

func (x *RocketComponent) GetSpecifications() map[string]string {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *RocketComponent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         *common.Money          `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_events_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{21}
}

func (x *InventoryItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryItem) GetPrice() *common.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *InventoryItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Batch events for efficiency
type BatchOrderEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*BaseEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EventCount    int32                  `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOrderEvents) Reset() {
	*x = BatchOrderEvents{}
	mi := &file_events_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOrderEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOrderEvents) ProtoMessage() {}

func (x *BatchOrderEvents) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOrderEvents.ProtoReflect.Descriptor instead.
func (*BatchOrderEvents) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{22}
}

func (x *BatchOrderEvents) GetEvents() []*BaseEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *BatchOrderEvents) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchOrderEvents) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BatchOrderEvents) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

// Dead letter event for failed processing
type DeadLetterEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OriginalEvent    *BaseEvent             `protobuf:"bytes,1,opt,name=original_event,json=originalEvent,proto3" json:"original_event,omitempty"`
	FailureReason    string                 `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	RetryCount       int32                  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	FirstFailedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_failed_at,json=firstFailedAt,proto3" json:"first_failed_at,omitempty"`
	LastFailedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_failed_at,json=lastFailedAt,proto3" json:"last_failed_at,omitempty"`
	ProcessingErrors []string               `protobuf:"bytes,6,rep,name=processing_errors,json=processingErrors,proto3" json:"processing_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeadLetterEvent) Reset() {
	*x = DeadLetterEvent{}
	mi := &file_events_events_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetterEvent) ProtoMessage() {}

func (x *DeadLetterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetterEvent.ProtoReflect.Descriptor instead.
func (*DeadLetterEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{23}
}

func (x *DeadLetterEvent) GetOriginalEvent() *BaseEvent {
	if x != nil {
		return x.OriginalEvent
	}
	return nil
}

func (x *DeadLetterEvent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *DeadLetterEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *DeadLetterEvent) GetFirstFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstFailedAt
	}
	return nil
}

func (x *DeadLetterEvent) GetLastFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFailedAt
	}
	return nil
}

func (x *DeadLetterEvent) GetProcessingErrors() []string {
	if x != nil {
		return x.ProcessingErrors
	}
	return nil
}

var File_events_events_proto protoreflect.FileDescriptor

const file_events_events_proto_rawDesc = "" +
	"\n" +
	"\x13events/events.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a\x13common/common.proto\"\x8c\x03\n" +
	"\tBaseEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12*\n" +
	"\x11data_content_type\x18\x06 \x01(\tR\x0fdataContentType\x12(\n" +
	"\x04data\x18\a \x01(\v2\x14.google.protobuf.AnyR\x04data\x12A\n" +
	"\n" +
	"extensions\x18\b \x03(\v2!.events.BaseEvent.ExtensionsEntryR\n" +
	"extensions\x12!\n" +
	"\fspec_version\x18\t \x01(\tR\vspecVersion\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\rEventEnvelope\x12'\n" +
	"\x05event\x18\x01 \x01(\v2\x11.events.BaseEventR\x05event\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.common.RequestMetadataR\bmetadata\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x05R\n" +
	"retryCount\x12I\n" +
	"\x12original_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11originalTimestamp\"\xdd\x01\n" +
	"\x11OrderCreatedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.events.OrderItemR\x05items\x120\n" +
	"\ftotal_amount\x18\x04 \x01(\v2\r.common.MoneyR\vtotalAmount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xee\x01\n" +
	"\x0eOrderPaidEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.common.MoneyR\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x123\n" +
	"\apaid_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"\x88\x02\n" +
	"\x17OrderStatusChangedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"old_status\x18\x03 \x01(\x0e2\x13.events.OrderStatusR\toldStatus\x122\n" +
	"\n" +
	"new_status\x18\x04 \x01(\x0e2\x13.events.OrderStatusR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"changed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"\xc9\x01\n" +
	"\x13OrderCancelledEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12=\n" +
	"\fcancelled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x12'\n" +
	"\x0frefund_required\x18\x05 \x01(\bR\x0erefundRequired\"\xcd\x02\n" +
	"\x15PaymentProcessedEvent\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.common.MoneyR\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.events.PaymentStatusR\x06status\x12=\n" +
	"\fprocessed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"\xfe\x01\n" +
	"\x12PaymentFailedEvent\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.common.MoneyR\x06amount\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x127\n" +
	"\tfailed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\"\x9d\x02\n" +
	"\x14AssemblyStartedEvent\x12\x1f\n" +
	"\vassembly_id\x18\x01 \x01(\tR\n" +
	"assemblyId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x127\n" +
	"\n" +
	"components\x18\x04 \x03(\v2\x17.events.RocketComponentR\n" +
	"components\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12<\n" +
	"\x1aestimated_duration_seconds\x18\x06 \x01(\x05R\x18estimatedDurationSeconds\"\x97\x02\n" +
	"\x16AssemblyCompletedEvent\x12\x1f\n" +
	"\vassembly_id\x18\x01 \x01(\tR\n" +
	"assemblyId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x126\n" +
	"\x17actual_duration_seconds\x18\x04 \x01(\x05R\x15actualDurationSeconds\x121\n" +
	"\aquality\x18\x05 \x01(\x0e2\x17.events.AssemblyQualityR\aquality\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x87\x02\n" +
	"\x13AssemblyFailedEvent\x12\x1f\n" +
	"\vassembly_id\x18\x01 \x01(\tR\n" +
	"assemblyId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x127\n" +
	"\tfailed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12+\n" +
	"\x11failed_components\x18\a \x03(\tR\x10failedComponents\"\xff\x01\n" +
	"\x16InventoryReservedEvent\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.events.InventoryItemR\x05items\x12;\n" +
	"\vreserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reservedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xdc\x01\n" +
	"\x16InventoryReleasedEvent\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.events.InventoryItemR\x05items\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12;\n" +
	"\vreleased_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"releasedAt\"\xe6\x01\n" +
	"\x15InventoryUpdatedEvent\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12!\n" +
	"\fold_quantity\x18\x03 \x01(\x05R\voldQuantity\x12!\n" +
	"\fnew_quantity\x18\x04 \x01(\x05R\vnewQuantity\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbe\x02\n" +
	"\x15NotificationSentEvent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.events.NotificationTypeR\x04type\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x122\n" +
	"\x06status\x18\a \x01(\x0e2\x1a.events.NotificationStatusR\x06status\x123\n" +
	"\asent_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xb4\x02\n" +
	"\x17NotificationFailedEvent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.events.NotificationTypeR\x04type\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x127\n" +
	"\tfailed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\"\xae\x01\n" +
	"\x10UserCreatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x85\x02\n" +
	"\x17UserSessionStartedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x9e\x01\n" +
	"\x15UserSessionEndedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"\xbb\x01\n" +
	"\tOrderItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12,\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\v2\r.common.MoneyR\tunitPrice\x12.\n" +
	"\vtotal_price\x18\x05 \x01(\v2\r.common.MoneyR\n" +
	"totalPrice\"\xba\x02\n" +
	"\x0fRocketComponent\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12%\n" +
	"\x0ecomponent_name\x18\x02 \x01(\tR\rcomponentName\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.events.ComponentTypeR\x04type\x12S\n" +
	"\x0especifications\x18\x04 \x03(\v2+.events.RocketComponent.SpecificationsEntryR\x0especifications\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x1aA\n" +
	"\x13SpecificationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\rInventoryItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12#\n" +
	"\x05price\x18\x04 \x01(\v2\r.common.MoneyR\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"\xb4\x01\n" +
	"\x10BatchOrderEvents\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.events.BaseEventR\x06events\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\x05R\n" +
	"eventCount\"\xc6\x02\n" +
	"\x0fDeadLetterEvent\x128\n" +
	"\x0eoriginal_event\x18\x01 \x01(\v2\x11.events.BaseEventR\roriginalEvent\x12%\n" +
	"\x0efailure_reason\x18\x02 \x01(\tR\rfailureReason\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x05R\n" +
	"retryCount\x12B\n" +
	"\x0ffirst_failed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rfirstFailedAt\x12@\n" +
	"\x0elast_failed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastFailedAt\x12+\n" +
	"\x11processing_errors\x18\x06 \x03(\tR\x10processingErrors*\xe2\x01\n" +
	"\vOrderStatus\x12\x18\n" +
	"\x14ORDER_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x1b\n" +
	"\x17ORDER_STATUS_ASSEMBLING\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_ASSEMBLED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x06\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\a*\xda\x01\n" +
	"\rPaymentStatus\x12\x1a\n" +
	"\x16PAYMENT_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x05\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x06*\xa0\x01\n" +
	"\x0fAssemblyQuality\x12\x1c\n" +
	"\x18ASSEMBLY_QUALITY_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aASSEMBLY_QUALITY_EXCELLENT\x10\x01\x12\x19\n" +
	"\x15ASSEMBLY_QUALITY_GOOD\x10\x02\x12\x19\n" +
	"\x15ASSEMBLY_QUALITY_FAIR\x10\x03\x12\x19\n" +
	"\x15ASSEMBLY_QUALITY_POOR\x10\x04*\xaa\x02\n" +
	"\rComponentType\x12\x1a\n" +
	"\x16COMPONENT_TYPE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15COMPONENT_TYPE_ENGINE\x10\x01\x12\x1c\n" +
	"\x18COMPONENT_TYPE_FUEL_TANK\x10\x02\x12\"\n" +
	"\x1eCOMPONENT_TYPE_GUIDANCE_SYSTEM\x10\x03\x12\x1e\n" +
	"\x1aCOMPONENT_TYPE_PAYLOAD_BAY\x10\x04\x12\x1e\n" +
	"\x1aCOMPONENT_TYPE_HEAT_SHIELD\x10\x05\x12\x1f\n" +
	"\x1bCOMPONENT_TYPE_LANDING_GEAR\x10\x06\x12 \n" +
	"\x1cCOMPONENT_TYPE_COMMUNICATION\x10\a\x12\x1d\n" +
	"\x19COMPONENT_TYPE_STRUCTURAL\x10\b*\xed\x02\n" +
	"\x10NotificationType\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_UNKNOWN\x10\x00\x12(\n" +
	"$NOTIFICATION_TYPE_ORDER_CONFIRMATION\x10\x01\x12*\n" +
	"&NOTIFICATION_TYPE_PAYMENT_CONFIRMATION\x10\x02\x12&\n" +
	"\"NOTIFICATION_TYPE_ASSEMBLY_STARTED\x10\x03\x12(\n" +
	"$NOTIFICATION_TYPE_ASSEMBLY_COMPLETED\x10\x04\x12!\n" +
	"\x1dNOTIFICATION_TYPE_ORDER_READY\x10\x05\x12%\n" +
	"!NOTIFICATION_TYPE_ORDER_CANCELLED\x10\x06\x12$\n" +
	" NOTIFICATION_TYPE_PAYMENT_FAILED\x10\a\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_SYSTEM_ALERT\x10\b*\xd8\x01\n" +
	"\x12NotificationStatus\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_SENT\x10\x02\x12!\n" +
	"\x1dNOTIFICATION_STATUS_DELIVERED\x10\x03\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_FAILED\x10\x04\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_BOUNCED\x10\x05B8Z6github.com/amiosamu/rocket-science/shared/proto/eventsb\x06proto3"

var (
	file_events_events_proto_rawDescOnce sync.Once
	file_events_events_proto_rawDescData []byte
)

func file_events_events_proto_rawDescGZIP() []byte {
	file_events_events_proto_rawDescOnce.Do(func() {
		file_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_events_proto_rawDesc), len(file_events_events_proto_rawDesc)))
	})
	return file_events_events_proto_rawDescData
}

var file_events_events_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_events_events_proto_goTypes = []any{
	(OrderStatus)(0),                // 0: events.OrderStatus
	(PaymentStatus)(0),              // 1: events.PaymentStatus
	(AssemblyQuality)(0),            // 2: events.AssemblyQuality
	(ComponentType)(0),              // 3: events.ComponentType
	(NotificationType)(0),           // 4: events.NotificationType
	(NotificationStatus)(0),         // 5: events.NotificationStatus
	(*BaseEvent)(nil),               // 6: events.BaseEvent
	(*EventEnvelope)(nil),           // 7: events.EventEnvelope
	(*OrderCreatedEvent)(nil),       // 8: events.OrderCreatedEvent
	(*OrderPaidEvent)(nil),          // 9: events.OrderPaidEvent
	(*OrderStatusChangedEvent)(nil), // 10: events.OrderStatusChangedEvent
	(*OrderCancelledEvent)(nil),     // 11: events.OrderCancelledEvent
	(*PaymentProcessedEvent)(nil),   // 12: events.PaymentProcessedEvent
	(*PaymentFailedEvent)(nil),      // 13: events.PaymentFailedEvent
	(*AssemblyStartedEvent)(nil),    // 14: events.AssemblyStartedEvent
	(*AssemblyCompletedEvent)(nil),  // 15: events.AssemblyCompletedEvent
	(*AssemblyFailedEvent)(nil),     // 16: events.AssemblyFailedEvent
	(*InventoryReservedEvent)(nil),  // 17: events.InventoryReservedEvent
	(*InventoryReleasedEvent)(nil),  // 18: events.InventoryReleasedEvent
	(*InventoryUpdatedEvent)(nil),   // 19: events.InventoryUpdatedEvent
	(*NotificationSentEvent)(nil),   // 20: events.NotificationSentEvent
	(*NotificationFailedEvent)(nil), // 21: events.NotificationFailedEvent
	(*UserCreatedEvent)(nil),        // 22: events.UserCreatedEvent
	(*UserSessionStartedEvent)(nil), // 23: events.UserSessionStartedEvent
	(*UserSessionEndedEvent)(nil),   // 24: events.UserSessionEndedEvent
	(*OrderItem)(nil),               // 25: events.OrderItem
	(*RocketComponent)(nil),         // 26: events.RocketComponent
	(*InventoryItem)(nil),           // 27: events.InventoryItem
	(*BatchOrderEvents)(nil),        // 28: events.BatchOrderEvents
	(*DeadLetterEvent)(nil),         // 29: events.DeadLetterEvent
	nil,                             // 30: events.BaseEvent.ExtensionsEntry
	nil,                             // 31: events.RocketComponent.SpecificationsEntry
	(*timestamppb.Timestamp)(nil),   // 32: google.protobuf.Timestamp
	(*anypb.Any)(nil),               // 33: google.protobuf.Any
	(*common.RequestMetadata)(nil),  // 34: common.RequestMetadata
	(*common.Money)(nil),            // 35: common.Money
}
var file_events_events_proto_depIdxs = []int32{
	32, // 0: events.BaseEvent.time:type_name -> google.protobuf.Timestamp
	33, // 1: events.BaseEvent.data:type_name -> google.protobuf.Any
	30, // 2: events.BaseEvent.extensions:type_name -> events.BaseEvent.ExtensionsEntry
	6,  // 3: events.EventEnvelope.event:type_name -> events.BaseEvent
	34, // 4: events.EventEnvelope.metadata:type_name -> common.RequestMetadata
	32, // 5: events.EventEnvelope.original_timestamp:type_name -> google.protobuf.Timestamp
	25, // 6: events.OrderCreatedEvent.items:type_name -> events.OrderItem
	35, // 7: events.OrderCreatedEvent.total_amount:type_name -> common.Money
	32, // 8: events.OrderCreatedEvent.created_at:type_name -> google.protobuf.Timestamp
	35, // 9: events.OrderPaidEvent.amount:type_name -> common.Money
	32, // 10: events.OrderPaidEvent.paid_at:type_name -> google.protobuf.Timestamp
	0,  // 11: events.OrderStatusChangedEvent.old_status:type_name -> events.OrderStatus
	0,  // 12: events.OrderStatusChangedEvent.new_status:type_name -> events.OrderStatus
	32, // 13: events.OrderStatusChangedEvent.changed_at:type_name -> google.protobuf.Timestamp
	32, // 14: events.OrderCancelledEvent.cancelled_at:type_name -> google.protobuf.Timestamp
	35, // 15: events.PaymentProcessedEvent.amount:type_name -> common.Money
	1,  // 16: events.PaymentProcessedEvent.status:type_name -> events.PaymentStatus
	32, // 17: events.PaymentProcessedEvent.processed_at:type_name -> google.protobuf.Timestamp
	35, // 18: events.PaymentFailedEvent.amount:type_name -> common.Money
	32, // 19: events.PaymentFailedEvent.failed_at:type_name -> google.protobuf.Timestamp
	26, // 20: events.AssemblyStartedEvent.components:type_name -> events.RocketComponent
	32, // 21: events.AssemblyStartedEvent.started_at:type_name -> google.protobuf.Timestamp
	2,  // 22: events.AssemblyCompletedEvent.quality:type_name -> events.AssemblyQuality
	32, // 23: events.AssemblyCompletedEvent.completed_at:type_name -> google.protobuf.Timestamp
	32, // 24: events.AssemblyFailedEvent.failed_at:type_name -> google.protobuf.Timestamp
	27, // 25: events.InventoryReservedEvent.items:type_name -> events.InventoryItem
	32, // 26: events.InventoryReservedEvent.reserved_at:type_name -> google.protobuf.Timestamp
	32, // 27: events.InventoryReservedEvent.expires_at:type_name -> google.protobuf.Timestamp
	27, // 28: events.InventoryReleasedEvent.items:type_name -> events.InventoryItem
	32, // 29: events.InventoryReleasedEvent.released_at:type_name -> google.protobuf.Timestamp
	32, // 30: events.InventoryUpdatedEvent.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 31: events.NotificationSentEvent.type:type_name -> events.NotificationType
	5,  // 32: events.NotificationSentEvent.status:type_name -> events.NotificationStatus
	32, // 33: events.NotificationSentEvent.sent_at:type_name -> google.protobuf.Timestamp
	4,  // 34: events.NotificationFailedEvent.type:type_name -> events.NotificationType
	32, // 35: events.NotificationFailedEvent.failed_at:type_name -> google.protobuf.Timestamp
	32, // 36: events.UserCreatedEvent.created_at:type_name -> google.protobuf.Timestamp
	32, // 37: events.UserSessionStartedEvent.started_at:type_name -> google.protobuf.Timestamp
	32, // 38: events.UserSessionStartedEvent.expires_at:type_name -> google.protobuf.Timestamp
	32, // 39: events.UserSessionEndedEvent.ended_at:type_name -> google.protobuf.Timestamp
	35, // 40: events.OrderItem.unit_price:type_name -> common.Money
	35, // 41: events.OrderItem.total_price:type_name -> common.Money
	3,  // 42: events.RocketComponent.type:type_name -> events.ComponentType
	31, // 43: events.RocketComponent.specifications:type_name -> events.RocketComponent.SpecificationsEntry
	35, // 44: events.InventoryItem.price:type_name -> common.Money
	6,  // 45: events.BatchOrderEvents.events:type_name -> events.BaseEvent
	32, // 46: events.BatchOrderEvents.created_at:type_name -> google.protobuf.Timestamp
	6,  // 47: events.DeadLetterEvent.original_event:type_name -> events.BaseEvent
	32, // 48: events.DeadLetterEvent.first_failed_at:type_name -> google.protobuf.Timestamp
	32, // 49: events.DeadLetterEvent.last_failed_at:type_name -> google.protobuf.Timestamp
	50, // [50:50] is the sub-list for method output_type
	50, // [50:50] is the sub-list for method input_type
	50, // [50:50] is the sub-list for extension type_name
	50, // [50:50] is the sub-list for extension extendee
	0,  // [0:50] is the sub-list for field type_name
}

func init() { file_events_events_proto_init() }
func file_events_events_proto_init() {
	if File_events_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_events_proto_rawDesc), len(file_events_events_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_events_proto_goTypes,
		DependencyIndexes: file_events_events_proto_depIdxs,
		EnumInfos:         file_events_events_proto_enumTypes,
		MessageInfos:      file_events_events_proto_msgTypes,
	}.Build()
	File_events_events_proto = out.File
	file_events_events_proto_goTypes = nil
	file_events_events_proto_depIdxs = nil
}
